### ISSUE TITLE
Annotate the OpenNeuro datasets

### ISSUE THREAD

**Issue by surchs** [neurobagel/bulk_annotations#2]
Go through the OpenNeuro datasets using the file created in #1  and annotate them so that we can create .json data dictionaries for each of them.

Remi has created one big [.tsv with datasets from open neuro](https://github.com/neurobagel/bulk_annotations/blob/19b530a9af7920d4a16a75717237a078686cbf00/outputs/bulk_annotation_levels.tsv).

For now the easiest seems to be GDrive. So here is a[ Google Spread file corresponding to the .tsv](https://docs.google.com/spreadsheets/d/1_6dnAjl2B2xse3uEB9UgKQziZeduZ9MDAVtUPW5IwIY/edit?usp=drive_link).

- [x] #10
- [x] Annotate the rest of OpenNeuro datasets

ToDo:
- [x] put this .tsv in a place where it can be incrementally annotated
- [x] figure out how to correctly annotate assessment tools
- [x] describe the annotation process (either in internal docs or in this repo)

**Comment by surchs** [comment]
Blocked by #8

**Comment by surchs** [comment]
One issue is that we don't currently have a way of annotating the transform heuristic for things we believe are "Age". So there may have to be a second stage where we either do that manually or confirm the automatic guesses done by the tool

**Comment by surchs** [comment]
We have 448 datasets in there. After a quick parsing, I now think that the best way to get through this thing is to do it in one pass as a big blob. The main reason for that is that there are (unsurprisingly) a ton of repetitions / similarities across datasets. So breaking things up by dataset would not be very useful. We could break things up by alphabetized column names, but I think the overall time investment for one person is still going to be reasonable (i.e. < 3 work days). So I'll just finish it

**Comment by Remi-Gau** [comment]
Regarding keeping the version of the tsv we will we have once you are done annotating, I was thinking we could actually keep it in this repo.
I could try to improve the original script that I had written so it can be run in "update" mode only so we add more datasets to it or update some rows of the upstream datasets get updated on open neuro.

**Comment by Remi-Gau** [comment]
Which makes me think we should probably track the version of the datasets we are annotating.
I doubt most of those datasets have a changelog so I suspect tracking the commit shasum.

**Comment by surchs** [comment]
This issue is done now (i.e. the .tsv is fully annotated). Quick note how to read it for a reviewer:

Meta-signal for annotation:
- Decision: cannot model this type
  - keep: can be treated as successfully annotated
  - drop: can be treated as a user supplied column that was not annotated with Neurobagel
- DropReason:
  - model: data might be fine, but we don't have a variable in our datamodel for this type of thing
  - vocabulary: our data model has a variable for this, but the corresponding vocabulary doesn't have a fitting controlled term (most often for Assessments)
  - ambiguity: given the info on the row and column, I couldn't figure out what this is supposed to be (might be worth a second look during review)
  - quality: didn't annotate because something seems seriously wrong with it

Actual annotation:
- controlled_term: 
  - for is_row (sic) = TRUE: the neurobagel model variable this column is about (e.g. nb:Sex, nb:Diagnosis)...
  - for is_row = False: the controlled term from the correct vocabulary (for this column type), or nb:MissingValue
- isPartOf: for columns of type nb:Assessment: the cognitive atlas term of the cognitive assessment that this column belongs to

**Comment by alyssadai** [comment]
(Adding myself as an additional assignee to this issue to indicate that I reviewed it - not sure we have a better way to handle these types of non-PR reviews yet)

Thanks @surchs for taking this on!! And with seriously impressive speed 🎉 

I wasn't sure what would be most helpful from a reviewer in this case, but what I did is go through all the rows that had an `ambiguity` DropReason to see if I could figure out an annotation, as well as quickly skim the rows with a `model` DropReason. I've added a new column "Annotator" to the spreadsheet with my initials (AD) in rows where I ended up changing the annotation or meta-annotation.

There were generally three types of changes I made (all affected rows are denoted with AD in the Annotator column):
- `ambiguity` "drop" rows -> "keep" rows with annotations based on info I could easily glean from the OpenNeuro dataset pages
- `ambiguity` "drop" rows -> "drop" rows with a more specific DropReason (I've also added comments in the Notes column where relevant)
  - I noticed that some rows (tsv columns) cannot currently be properly annotated because they use numeric coding for categorical levels (e.g., 1 for female, 0 for not female), so the levels are not properly expanded in the spreadsheet. I think this is related to https://github.com/neurobagel/bulk_annotations/issues/11. I flagged these rows using a new DropReason called `coding` 
- Notes on `model` "drop" rows that I thought could be annotated, including the relevant controlled terms (would like you to have another look to see if you agree)

Have a look and let me know if you want to discuss any of the points further. Hope that helped!

**Comment by surchs** [comment]
Thanks @alyssadai. This is very helpful. 
I noticed some of the `IsPartOf` terms you added (i.e. index 105-124) have sequentially increasing numeric IDs.
This is a problem I noticed as well when you use the auto-fill feature on gspread to copy a term down a bunch of rows.
Gspread is trying to be smart and increments the IRI by 1 each time. I think there is a way to prevent that, or you just plain old copy-paste the term into the whole section.

I pinged you on an example, please take a look at the terms you added to see if this happened in other places as well.

**Comment by alyssadai** [comment]
🤦‍♀️ _of course_ sheets did that.

Fixed! Thanks for catching that.
